U03 2 category movie
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #15
Opened 2024-09-13 08:24 UTC by dgonc

🎨 add the types of movie in MovieDetails

2024-09-13 08:37 UTC, dgonc commented on client/src/components/MovieDetails.jsx
> +  console.info("depuis movieDetail", movie);
Nécessaire pour la suite du développement de la branche

2024-09-17 07:10 UTC, kpeset requested changes

2024-09-17 07:10 UTC, kpeset commented on client/src/components/CategoryCard.jsx
> +  const getMoviesByCategories = async (type) => {
Je ne comprends pas l'utilité de la fonction ^^

2024-09-17 07:40 UTC, ChrisColesnicov commented
PR closed for the moment, feature not complete.

2024-09-17 07:40 UTC, closed without merging