U04 1 account logout
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #20
Opened 2024-09-18 16:42 UTC by ChrisColesnicov

Account login and logout is now complete, with new login handling, logout route, and much more.

2024-09-19 08:29 UTC, antoinefouga approved these changes
good job !

2024-09-19 08:55 UTC, dgonc approved these changes
👍🏻 good work !

2024-09-19 14:57 UTC, ChrisColesnicov commented on client/src/pages/Logout.jsx
> +    const timer =
Pour l'accessibilité et le feedback utilisateur, cela rend la navigation moins brutale à mon sens, et cela laisse le temps de digérer le fait qu'on a une confirmation de notre action de déconnexion.

2024-09-19 15:14 UTC, kpeset commented on client/src/pages/Logout.jsx
> +    const timer =
Mais ça donne l'impression que l'application rame.
C'est je pense problématique. Car de toute façon l'action est faite. On ne met des temps d'attente que lorsque l'application nous y oblige dans un soucis de performance. Là ça me semble un peu fake, donc pas très utile :)
Donc à supprimer  ^^

ps : à la rigueur pour quelque chose à enjeu de type redirection vers une interface bancaire pourquoi pas. Mais pas pour une DC ^^

2024-09-19 16:05 UTC, kpeset requested changes

2024-09-19 16:05 UTC, kpeset commented on client/src/pages/User.jsx
> +      <Link
Un Link c'est une balise a au final ^^
On met des onClick sur des boutons ;) pas sur des a.

2024-09-19 16:05 UTC, kpeset commented on client/src/pages/User.jsx
> +        onClick={() => {
Le onclick devra executer la requête api.
Les choses qui suivent (suppression du localstorage) doivent être faite dans le .then
Car là on execute les choses alors qu'on a même pas eu la confirmation du backend ;)

2024-09-19 16:05 UTC, kpeset commented on client/src/services/request.js
> +      localStorage.clear();
La promesse devra donc contenir la logique qui était à la base dans le onClick :)

2024-09-19 19:07 UTC, ChrisColesnicov commented
Et un composant dédié à tout ça ? et réutilisable ? et qui contient toute la logique ? mieux non ?
Si oui, le dernier commit contient tout ça 👍 
Si non, on fera autrement 👍

2024-09-20 09:05 UTC, kpeset approved these changes

2024-09-20 09:05 UTC, merged