U04 2 account delete
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #23
Opened 2024-09-20 14:50 UTC by ChrisColesnicov

CRUD complete for user with this feature.

2024-09-22 19:43 UTC, antoinefouga approved these changes
good job again !

2024-09-23 11:25 UTC, dgonc approved these changes
nice work !

2024-09-24 08:07 UTC, kpeset requested changes
Est-ce que cette feature permet à un user de delete son compte ?
A ce moment là, je suis plus partant pour récupérer l'id qui provient du token contenu dans le cookie :)
Plutôt que d'envoyer l'id via les params.

2024-09-24 10:18 UTC, kpeset approved these changes

2024-09-24 10:18 UTC, merged