U03 2 carrousel
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #24
Opened 2024-09-21 16:45 UTC by ChrisColesnicov

Home page is freshly painted, carrousel and css styling included.

2024-09-22 19:46 UTC, antoinefouga requested changes
very good job but you have 2 console.info in your Carousel.jsx ! line 10 and 11

2024-09-22 20:02 UTC, ChrisColesnicov commented
> very good job but you have 2 console.info in your Carousel.jsx ! line 10 and 11

Good eye !
Fixed :)

2024-09-23 11:10 UTC, dgonc approved these changes
👍 excited to see the result

2024-09-24 08:08 UTC, kpeset approved these changes

2024-09-24 08:08 UTC, merged