U33 admin delete
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #31
Opened 2024-09-24 15:38 UTC by antoinefouga

delete movie for adminPanel

2024-09-24 15:43 UTC, ChrisColesnicov approved these changes
yes !

2024-09-25 08:27 UTC, Sarahadelina approved these changes
sounds good

2024-09-25 13:27 UTC, kpeset requested changes

2024-09-25 13:27 UTC, kpeset commented on server/database/tables.js
> +tables.movie_category = new MovieCategoryRepository();
Jamais de snake case (malheureusement) en js.
On doit avoir tables.movieCategory ! Cela ne me plait guère mais c'est comme ça  !

N'oublie pas de le changer dans  le movieActions

2024-09-25 14:39 UTC, kpeset approved these changes

2024-09-25 14:40 UTC, merged