U01 user
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals pull request #7
Opened 2024-09-04 13:22 UTC by ChrisColesnicov

User Form with its own path is done, with css, and app rework.

2024-09-04 14:11 UTC, dgonc approved these changes
good job 👋

2024-09-04 14:13 UTC, antoinefouga approved these changes
good job !

2024-09-04 14:27 UTC, kpeset requested changes
Quelques changements à faire :)

2024-09-04 14:27 UTC, kpeset commented on client/src/App.jsx
>      <ul>
Pourquoi ne pas créer un composant navbar (qui contient une balise html nav) et l'appeler ici ? ;)

2024-09-04 14:27 UTC, kpeset commented on client/src/main.jsx
> +        action: async ({request}) => {
Ne pourrait on pas mettre toute cette logique dans un fichier js genre usersActions dans le dossier services et l'utiliser ici ?

2024-09-04 16:19 UTC, ChrisColesnicov commented on client/src/App.jsx
>      <ul>
du coup y a un menu burger maintenant.

2024-09-05 07:46 UTC, kpeset approved these changes
C'est bueno !

2024-09-05 07:46 UTC, kpeset commented on client/src/components/NavBar.jsx
> +    <nav className="navbar">
Retirer la classname à notre nav puisqu'on en à qu'une !

2024-09-05 07:46 UTC, kpeset commented on client/src/components/NavBar.jsx
> +    <nav className="navbar">
Ou alors donne le nom mobile

2024-09-05 07:47 UTC, merged